## Get Related Articles [GET /v1/articles/{id}/related-articles]

Get Related Articles of Article

+ Parameters
    + id: id (required) - article_id

+ Response 200 (application/json)
    + Body
        ```json
            {
                "status": {
                    "type": "OK",
                    "subtype": null,
                    "message": null
                },
                "data": [
                    {
                        "id": 1,
                        "title": "Article 1",
                        "content": "<html>...</html>",
                        "category_id": 1,
                        "author_id": 1,
                        "tag_id": 1,
                        "created_at": 1635823890,
                        "updated_at": 1635823890,
                    },
                ]
            }
        ```
